In [1]:
nd = 255.

In [2]:
import gdal

In [3]:
wells = glob.glob('./data/haines_tiffs/well_count*.tif')
gas = glob.glob('./data/haines_tiffs/gas_production_*.tif')
oil = glob.glob('./data/haines_tiffs/oil_production_*.tif')
treatments = glob.glob('./data/haines_tiffs/treatment_water_*.tif')
produced = glob.glob('./data/haines_tiffs/water_production_*.tif')

In [4]:
vars = [wells,gas,oil,treatments,produced]
varnames = ['wells','gas','oil','treatments','produced']

In [26]:
def get_minmax(fl):
    ds = gdal.Open(fl,gdal.GA_ReadOnly)
    band = ds.GetRasterBand(1)
    dat = np.array(ds.GetRasterBand(1).ReadAsArray(),np.float32)
    nd = band.GetNoDataValue()
    dat[dat==nd] = np.NaN
    n,m = dat.shape
    tmp = np.reshape(dat,(n*m))
    tmp = tmp[(np.isnan(tmp)==0) & (np.isinf(tmp) == 0)]
    return np.min(tmp),np.max(tmp),nd

In [34]:
for var,varname in zip(vars,varnames):
    out = []
    for fl in var:
        out.append(get_minmax(fl))
    min,max,nd = zip(*out)

    print('%s min: %f'%(varname,np.min(min)))
    print('%s max: %f'%(varname,np.max(max)))
    print('%s nodata: %f'%(varname,np.unique(nd)[0]))

wells min: 1.000000
wells max: 17.000000
wells nodata: 255.000000
gas min: 0.000000
gas max: 549919.000000
gas nodata: 65535.000000
oil min: 0.000000
oil max: 3101867.000000
oil nodata: 65535.000000
treatments min: 100.000000
treatments max: 109235784.000000
treatments nodata: -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000
produced min: 0.000000
produced max: 8532121.000000
produced nodata: 2147483647.000000


In [31]:
np.unique(nd)

array([ 255.])

In [15]:
tmp

array([], dtype=float16)

In [19]:
dat = np.array(ds.GetRasterBand(1).ReadAsArray(),dtype=np.float32)

In [20]:
dat

array([[  2.14748365e+09,   2.14748365e+09,   2.14748365e+09, ...,
          2.14748365e+09,   2.14748365e+09,   2.14748365e+09],
       [  2.14748365e+09,   2.14748365e+09,   2.14748365e+09, ...,
          2.14748365e+09,   2.14748365e+09,   2.14748365e+09],
       [  2.14748365e+09,   2.14748365e+09,   2.14748365e+09, ...,
          2.14748365e+09,   2.14748365e+09,   2.14748365e+09],
       ..., 
       [  2.14748365e+09,   2.14748365e+09,   2.14748365e+09, ...,
          2.14748365e+09,   2.14748365e+09,   2.14748365e+09],
       [  2.14748365e+09,   2.14748365e+09,   2.14748365e+09, ...,
          2.14748365e+09,   2.14748365e+09,   2.14748365e+09],
       [  2.14748365e+09,   2.14748365e+09,   2.14748365e+09, ...,
          2.14748365e+09,   2.14748365e+09,   2.14748365e+09]], dtype=float32)

In [14]:
ds = gdal.Open(fl,gdal.GA_ReadOnly)
dat = np.array(ds.GetRasterBand(1).ReadAsArray(),dtype=np.float16)
dat[dat==nd] = np.NaN
n,m = dat.shape
tmp = np.reshape(dat,(n*m))
tmp = tmp[(np.isnan(tmp)==0) & (np.isinf(tmp) == 0)]

In [48]:
from scipy import stats as ss

In [49]:
ss.mode(tmp)

ModeResult(mode=array([ 255.], dtype=float16), count=array([208702]))

In [40]:
tmp

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  2.,  1.,  1.,  1.,  1.,  2.,  1.,  2.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,
        1.,  2.,  1.,  1.,  1.,  1.,  3.,  1.,  1.,  1.,  1.,  1.,  1.,  1.], dtype=float16)